# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- pipeline

pool:
  namme: 'Windows Tests'
  vmImage: 'windows-2019'

steps:
- powershell: |
    "Testing: {0} ..." -f "powershell.exe"
  displayName: 'Test run Powershell'

- pwsh: |
    "Testing: {0} ..." -f "pwsh.exe"
  displayName: 'Test run Pwsh'
